### ISSUE TITLE
Create the Recent Submissions view

### ISSUE THREAD

**Issue by Decoder22** [PurdueHCR/PurdueHCR-Android#13]
This view will display the last 3 submissions that a user made, and it will give them a more button that will display the complete list of all points that they have submitted.

1. Create the XML File to display a design like the one in the UI Mockup on Slack.
2. Populate the view with the correct information.
3. Create a more button that when pressed, will display the PersonalPointLogListFragment

**Comment by andrewfhou** [comment]
Implemented by #21
